# Generated by Django 3.0 on 2020-02-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Event_Name', models.CharField(max_length=40)),
                ('Events_Details', models.CharField(max_length=1000)),
                ('Casts', models.CharField(max_length=100)),
                ('Poster', models.ImageField(upload_to='')),
                ('Trailer', models.FileField(null=True, upload_to='videos/')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('movie_Name', models.CharField(max_length=40)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Movie_Details', models.CharField(max_length=1000)),
                ('Casts', models.CharField(max_length=100)),
                ('Poster', models.ImageField(upload_to='')),
                ('Trailer', models.FileField(null=True, upload_to='videos/')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=40)),
                ('Contact_Number', models.CharField(max_length=50)),
                ('Profile_Pic', models.ImageField(default='defaultimg.png', upload_to='images/')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('S_No', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Venue_Name', models.CharField(max_length=30)),
                ('Venue_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'venues',
            },
        ),
        migrations.CreateModel(
            name='Mbooking',
            fields=[
                ('Mbooking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Bookedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('M_Venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Venues')),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Movies')),
            ],
            options={
                'db_table': 'Mbooking',
            },
        ),
        migrations.CreateModel(
            name='Ebooking',
            fields=[
                ('Ebooking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Bookedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('E_Venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Venues')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Events')),
            ],
            options={
                'db_table': 'Ebooking',
            },
        ),
    ]
